# DATA Practical 3 - Model Answers




## All You Need to Know About Google Play Store

**Google Play store** ([https://play.google.com/store?hl=en](https://play.google.com/store?hl=en)) is a digital distribution service operated and developed by Google. It serves as the official app store for the Android operating system, allowing users to browse and download applications developed with the Android software development kit (SDK) and published through Google. [Wikipedia](https://en.wikipedia.org/wiki/Google_Play).

**DataVision** has scraped the Google Play store  and acquired data for several Android applications. Since data from the Play Store apps has great potential to drive app-making businesses to success, DataVision wants to investigate whether any actionable insights can be drawn for developers to work on and capture the Android market!

#### Your tasks are to explore this dataset and generade actionable knowledge. 


#### This Jupyter Notebook will be presented to  Google stakeholders who have limited knowledge about data science. So, your findings should be complemented by a suitable justification explaining what you observe and, when applicable, what does this observation  mean and, possibly, why it occurs.

* For each question (task) a description is provided accompanied (most of the time) by two cells: one for writing the Python code and another for providing the justification. Feel free to add more cells if you feel they are needed, but keep the cells corresponding to the same question close by.



(1) Read **Chapter 2 - Introduction to NumPy from the Python Data Science Handbook** (https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html)


(2) Read **Chapter 3: Dapa Manipulation with Pandas from the Python Data Science Handbook** (https://jakevdp.github.io/PythonDataScienceHandbook/03.00-introduction-to-pandas.html)

(3) If you haven't already done so, complete the tutorial on Numpy and Pandas to become familiar with the libraries.


**Numpy API Reference**: https://numpy.org/doc/stable/reference

**Pandas API Reference**:  https://pandas.pydata.org/pandas-docs/stable/reference/index.html

***

### Part 1: Getting dataset

The Google dataset is available on VLE (look for googleplaystore.csv in the Practicals section)

Before doing the tasks below, you may want to explore the dataset using a spreadsheet editor (e.g., Excel) to get a high-level view of the dataset.

**T1) Assign loaded Google PlayStore dataset (.csv) to a variable called df using the pandas library**

**Note**: You have to download the dataset on your local machine and then load it onto the Jupyter Notebook

In [1]:
import pandas as pd 
import numpy as np

# Answer:
fileCSV = "googlePlaystore.csv"

In [2]:
#Write your answer here
df = pd.read_csv(fileCSV)

***

### Part 2: Checking, cleaning and analysing the dataset

**You need to use the dataframe df obtained in Part 1 to perform all of the following tasks.**

**T2i) Print the first 10 records of the dataframe**

In [3]:
#Write your answer here
df.head(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Truth or Dare Pro,DATING,NaN,0,20M,50+,Paid,$1.49,Teen,Dating,"September 1, 2017",1,4.0 and up
1,"Private Dating, Hide App- Blue for PrivacyHider",DATING,NaN,0,18k,100+,Paid,$2.99,Everyone,Dating,"July 25, 2017",1.0.1,4.0 and up
2,Dating White Girls,DATING,NaN,0,3.6M,50+,Free,0,Mature 17+,Dating,"July 20, 2018",1,4.0 and up
3,Geeks Dating,DATING,NaN,0,13M,50+,Free,0,Mature 17+,Dating,"July 10, 2018",1,4.1 and up
4,CAM5678 Video Chat,DATING,NaN,0,39M,500+,Free,0,Mature 17+,Dating,"July 13, 2018",5.5.8,4.0.3 and up
5,Video chat live advices,DATING,NaN,0,8.0M,100+,Free,0,Everyone,Dating,"July 10, 2018",1,3.0 and up
6,Pet Lovers Dating,DATING,NaN,0,14M,10+,Free,0,Mature 17+,Dating,"July 9, 2018",1,4.1 and up
7,Latin Dating,DATING,NaN,0,13M,10+,Free,0,Mature 17+,Dating,"July 9, 2018",1,4.1 and up
8,Wifi Mingle,DATING,NaN,0,10.0M,10+,Free,0,Everyone,Dating,"July 27, 2018",1.3,4.4 and up
9,HOW TO ASK A GIRL OUT,DATING,NaN,0,19M,10+,Free,0,Everyone,Dating,"July 16, 2018",1,4.0.3 and up

**T2ii) Print the last 3 records of the dataframe**

In [4]:
#Write your answer here

df.tail(3)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,WhatsApp Messenger,COMMUNICATION,4.4,69119316,Varies with device,"1,000,000,000+",Free,0,Everyone,Communication,"August 3, 2018",Varies with device,Varies with device
10837,Facebook,SOCIAL,4.1,78128208,Varies with device,"1,000,000,000+",Free,0,Teen,Social,"August 3, 2018",Varies with device,Varies with device
10838,Facebook,SOCIAL,4.1,78158306,Varies with device,"1,000,000,000+",Free,0,Teen,Social,"August 3, 2018",Varies with device,Varies with device

**T3) Get general info about the dataset**

* Hint: use the info() method of the dataframe

In [5]:
#Write your answer here

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10839 entries, 0 to 10838
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10839 non-null  str
 1   Category        10839 non-null  str
 2   Rating          9365 non-null   float64
 3   Reviews         10839 non-null  int64
 4   Size            10839 non-null  str
 5   Installs        10839 non-null  str
 6   Type            10838 non-null  str
 7   Price           10839 non-null  str
 8   Content Rating  10839 non-null  str
 9   Genres          10839 non-null  str
 10  Last Updated    10839 non-null  str
 11  Current Ver     10831 non-null  str
 12  Android Ver     10837 non-null  str
dtypes: float64(1), int64(1), str(11)
memory usage: 1.1 MB

**T4) Explore the dataset and try to understand the meaning of each column. For each column, write its meaning and its data type**

- App:            Name of the application (Text)
- Category:       Category the app belongs to (Categorical - nominal)
- Rating:         The Star rating of the app (Numerical - Discrete)
- Reviews:        How many reviews there are (Numerical - Discrete)
- Size:           How large the app size is  (Numerical - Continuos)
- Installs:       How many downloads the app has (Numerical - Discrete)
- Type:           If app is paid or free (Categorical - Ordinal)
- Price:

**T5) Find the size of the dataset by reporting the number of rows and columns.**

In [6]:
#Write your answer here


#(Note: if you use the size property of a Dataframe it will output the product of #rows x #columns)
print("dataframe is" , df.shape[0] , "Rows")
print("dataframe is " , df.shape[1] , " Cols")

dataframe is 10839 Rows
dataframe is  13  Cols

**T6) Get the name of the columns of the dataframe**

In [7]:
#Write your answer here
print(df.columns)

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='str')

**T7) Rename the column names by removing spaces between words and replacing Ver with Version.**

In [8]:
#Write your answer here
df.columns = df.columns.str.replace(" ", "")
df.columns = df.columns.str.replace("Ver", "Version")
print(df.columns)

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'ContentRating', 'Genres', 'LastUpdated', 'CurrentVersion',
       'AndroidVersion'],
      dtype='str')

**T8) How many duplicated records exist?**

* **Note**: A record is duplicated if all its entries are identical with another record
* Hint: Check the duplicated method in Pandas

In [9]:
#Write your answer here
dupe = df.duplicated()
dupeRecord = df[dupe]
print(dupe)

0        False
1        False
2        False
3        False
4        False
         ...
10834    False
10835    False
10836     True
10837    False
10838    False
Length: 10839, dtype: bool

**T9 From the duplicated records, determine how many correspond to apps whose name in the App column contains the phrase blood pressure, and print them**

In [10]:
#Write your answer here

dupeRecord[dupeRecord["App"].str.contains("blood pressure")]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, ContentRating, Genres, LastUpdated, CurrentVersion, AndroidVersion]
Index: []

**T10) Let's look more closely into the dataset. Are there more duplicates?**

**Hint:** Check the duplicated function of Pandas to understand how the function operates. Do you need to specify what information to consider when checking for duplicates?

In [11]:
#Write your answer here
allDupe = df[df.duplicated(keep=False)]
print(allDupe.count())

App               893
Category          893
Rating            876
Reviews           893
Size              893
Installs          893
Type              893
Price             893
ContentRating     893
Genres            893
LastUpdated       893
CurrentVersion    893
AndroidVersion    893
dtype: int64

**T11) Identify the application with the highest number of duplicate records. Report how many duplicate records it has and list the details of these duplicate entries.**

**Hint:** How can you count the records of a dataframe?

In [12]:
#Write your answer here

print(allDupe.App.value_counts())

# CBS Sports App - Scores, News, Stats & Watch Live has the most duplicates at 7
print(df[df.App.str.contains("CBS Sports App - Scores, News, Stats & Watch Live")])

App
CBS Sports App - Scores, News, Stats & Watch Live     7
ESPN                                                  6
Bleacher Report: sports news, scores, & highlights    5
theScore: Live Sports Scores, News, Stats & Videos    5
Meetup                                                4
                                                     ..
Subway Surfers                                        2
Clash of Clans                                        2
Messenger – Text and Video Chat for Free              2
Instagram                                             2
WhatsApp Messenger                                    2
Name: count, Length: 400, dtype: int64
                                                    App Category  Rating  \
8594  CBS Sports App - Scores, News, Stats & Watch Live   SPORTS     4.3
8595  CBS Sports App - Scores, News, Stats & Watch Live   SPORTS     4.3
8596  CBS Sports App - Scores, News, Stats & Watch Live   SPORTS     4.3
8597  CBS Sports App - Scores, News, Stats & Watch Live   SPORTS     4.3
8598  CBS Sports App - Scores, News, Stats & Watch Live   SPORTS     4.3
8599  CBS Sports App - Scores, News, Stats & Watch Live   SPORTS     4.3
8600  CBS Sports App - Scores, News, Stats & Watch Live   SPORTS     4.3
8601  CBS Sports App - Scores, News, Stats & Watch Live   SPORTS     4.3

      Reviews                Size    Installs  Type Price ContentRating  \
8594    91031  Varies with device  5,000,000+  Free     0      Everyone
8595    91031  Varies with device  5,000,000+  Free     0      Everyone
8596    91031  Varies with device  5,000,000+  Free     0      Everyone
8597    91031  Varies with device  5,000,000+  Free     0      Everyone
8598    91033  Varies with device  5,000,000+  Free     0      Everyone
8599    91033  Varies with device  5,000,000+  Free     0      Everyone
8600    91033  Varies with device  5,000,000+  Free     0      Everyone
8601    91035  Varies with device  5,000,000+  Free     0      Everyone

      Genres     LastUpdated      CurrentVersion AndroidVersion
8594  Sports  August 4, 2018  Varies with device     5.0 and up
8595  Sports  August 4, 2018  Varies with device     5.0 and up
8596  Sports  August 4, 2018  Varies with device     5.0 and up
8597  Sports  August 4, 2018  Varies with device     5.0 and up
8598  Sports  August 4, 2018  Varies with device     5.0 and up
8599  Sports  August 4, 2018  Varies with device     5.0 and up
8600  Sports  August 4, 2018  Varies with device     5.0 and up
8601  Sports  August 4, 2018  Varies with device     5.0 and up

In [13]:
#Write your answer here

**T12) Examine the records for the app you identified in Task T11. Why do you think duplicate records exist for this app? Provide your reasoning.**

In [14]:
#Write your answer here
#Could be for different devices due to the varies with device.

Possible reasons include:

* The only difference between some entries is the Category (e.g. GAME vs FAMILY), which suggests that the app may have been classified inconsistently.
* Several entries show different numbers of reviews, which indicates that the records may have been captured at different time points during data collection.

**T13) Remove duplicate records from the dataframe, assuming the data was collected sequentially. Decide which entry to keep, and then print the number of rows and columns in the updated dataset.**

**Hint:** You may want to check the documentation of the drop_duplicates function

In [15]:
#Write your answer here
df.drop_duplicates(subset="App", keep="first", inplace=True)
print(df.count())

App               9658
Category          9658
Rating            8194
Reviews           9658
Size              9658
Installs          9658
Type              9657
Price             9658
ContentRating     9658
Genres            9658
LastUpdated       9658
CurrentVersion    9650
AndroidVersion    9656
dtype: int64

**T14) How many unique values exist under the Price variable? Print the first five unique prices.**

In [47]:
#Write your answer here
for i in range(5):
    print(df.Price.unique()[i])

$1.49
$2.99
0
$14.99
$5.99

**T15i) Write a function moneyWithoutCurrencySymbol that takes a string and returns the string as a float without the currency symbol (if exists)**

In [48]:
#Write your answer here

def moneyWithoutCurrencySymbol(money : str) -> float:
    return float(money.replace("$", ""))

**T15ii) Convert the Price column into a float variable. Before performing the conversion, display the first 5 values and the data type of the column. Then repeat the same checks after conversion to confirm that the transformation was successful.**

**Hint:**

* You may want to use the function from task T15i
* You may want to check https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.apply.html
* Alternatively, you may want to check https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_numeric.html

In [49]:
#Write your answer here

for i in range(5):
    print(moneyWithoutCurrencySymbol(
        df.Price.unique()[i]
    ))

1.49
2.99
0.0
14.99
5.99

**T16i) How many missing data (NaN) exist for each variable?**

In [52]:
#Write your answer here

print(df.notna().count() - df.count())

App                  0
Category             0
Rating            1464
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
ContentRating        0
Genres               0
LastUpdated          0
CurrentVersion       8
AndroidVersion       2
dtype: int64

**T16ii) Impute the missing values in the categorical columns (Type, CurrentVersion, and AndroidVersion) with the mode of each column. Show the number of missing values in these columns before and after the imputation.**

**Hint:** Check Chapter 3 of the Python Data Science Handbook

In [20]:
#Write your answer here

**T16iii) What would be an appropriate value to impute for the categorical columns "Rating"? Apply the imputation.**

**Note:** Different imputation may be possible depending on your assumption.

In [21]:
#Write your answer here

**T17i) Display all the unique values that appear in the Installs column.**

In [22]:
#Write your answer here

**T17ii) Based on the unique values you found in Task T17i, identify any inconsistent entries in the Installs column. If such values exist, suggest and apply appropriate cleaning steps, then verify the result**

* Hint: Check the Pandas method loc (https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc)

In [23]:
#Write your answer here

**T18) Are there any logical inconsistencies in the *Type* and *Price* variables? Specifically, are there any applications labelled as *Free* for which you have to pay, or any applications labelled as *Paid* that are available for free? Verify the integrity of the dataset using these conditions.**

In [24]:
#Write your answer here

**T19i) Are there any logical inconsistencies in the *Reviews* and *Rating* variables? Specifically, are there any applications with zero reviews that nevertheless have a rating greater than zero? Verify the integrity of the dataset using this condition.**

In [25]:
#Write your answer here

**T19ii) Based on the results from task T19i, suggest an appropriate method to correct the identified inconsistency.**

In [26]:
#Write your answer here

**T20i) Get some descriptive statistics for the dataset**

In [27]:
#Write your answer here

**T20i) Plot the histogram of the Price variable using 20 bins**

* Hint: See https://www.w3schools.com/python/matplotlib_histograms.asp

In [28]:
#Write your answer here

**T21i) Investigate whether the *Price* variable contains any outliers. Should any preparatory steps be taken before this analysis? Apply the IQR method to examine the data and describe your observations.**

In [29]:
#We need to keep only the Paid applications
#Write your answer here

In [30]:
#Write your answer here

**T21ii) Do the same using the standard deviation method for identifying outliers for the Price**

In [31]:
#Write your answer here

**T22) Use an appropriate method to investigate the potential existence of outliers for the Reviews variable**

In [32]:
#Write your answer here

In [33]:
#Write your answer here

In [34]:
#Write your answer here

**T23) (Funny) What is weird about the most expensive applications which are at or above the 99.9th percentile?**

In [35]:
#Write your answer here

## Bonus

**T24i) Check the type of the variable indicating the last time the application was updated and convert it into the appropriate format**

**Hint:** 

* You may want to check https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html

* Pay attention to the date format and the month type

* You may also want to check https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html

In [36]:
#Write your answer here

**T24ii) Which application was updated least recently and when did this happen?**

In [37]:
#Write your answer here

**T25) Create a new column that indicates the difference between the last updated variable and the current date.**

In [38]:
#Write your answer here

**T26i) Perform the necessary processing tasks to convert the Size variable into a float using a common metric (i.e., which will enable to compare records between each other using the size value). Set records whose value is "Varies with device" to 1**

In [39]:
#Write your answer here

**T26ii) Which is the smallest application and what is its size?**

In [40]:
#Write your answer here

**T26iii) Among the largest applications, which category is the most common, and which applications belong to this category? **

In [41]:
#Write your answer here

### Should you finish earlier/want to practice at home, you could

* Check that the values of Rating variable is within the limits [0,5]
* Save the updated file as a new table
* Any other analysis that you might could generate some useful insight.